import type { User, ClassItem, AttendanceSession, AttendanceLog, ComplaintRequest, AuditLog, SystemHealth } from '../types'

export const INITIAL_USERS: User[] = [
  {
    id: 1,
    userId: 'SV20240128',
    username: 'khoa.tm',
    fullName: 'Trần Minh Khoa',
    email: 'khoa.tm@fpt.edu.vn',
    role: 'student',
    isActive: true,
    department: 'Công nghệ thông tin',
    hasFaceRegistered: true,
    avatar: 'TK',
  },
  {
    id: 2,
    userId: 'GV2021042',
    username: 'lan.nt',
    fullName: 'Nguyễn Thị Lan',
    email: 'lan.nt@fpt.edu.vn',
    role: 'teacher',
    isActive: true,
    department: 'Công nghệ phần mềm',
    hasFaceRegistered: true,
    avatar: 'LT',
  },
  {
    id: 3,
    userId: 'AD2020008',
    username: 'long.pd',
    fullName: 'Phạm Đức Long',
    email: 'long.pd@fpt.edu.vn',
    role: 'admin',
    isActive: true,
    department: 'Phòng Đào tạo & Khảo thí',
    hasFaceRegistered: true,
    avatar: 'PL',
  },
  {
    id: 4,
    userId: 'SV20240129',
    username: 'anh.nm',
    fullName: 'Nguyễn Minh Anh',
    email: 'anh.nm@fpt.edu.vn',
    role: 'student',
    isActive: true,
    department: 'Công nghệ thông tin',
    hasFaceRegistered: true,
    avatar: 'MA',
  },
  {
    id: 5,
    userId: 'SV20240204',
    username: 'huy.tq',
    fullName: 'Trần Quốc Huy',
    email: 'huy.tq@fpt.edu.vn',
    role: 'student',
    isActive: true,
    department: 'Công nghệ thông tin',
    hasFaceRegistered: true,
    avatar: 'QH',
  },
  {
    id: 6,
    userId: 'SV20240312',
    username: 'thao.lp',
    fullName: 'Lê Phương Thảo',
    email: 'thao.lp@fpt.edu.vn',
    role: 'student',
    isActive: true,
    department: 'Công nghệ thông tin',
    hasFaceRegistered: true,
    avatar: 'PT',
  },
  {
    id: 7,
    userId: 'SV20240405',
    username: 'bao.pg',
    fullName: 'Phạm Gia Bảo',
    email: 'bao.pg@fpt.edu.vn',
    role: 'student',
    isActive: true,
    department: 'Hệ thống thông tin',
    hasFaceRegistered: false,
    avatar: 'GB',
  },
  {
    id: 8,
    userId: 'SV20230104',
    username: 'nam.vh',
    fullName: 'Vũ Hoàng Nam',
    email: 'nam.vh@fpt.edu.vn',
    role: 'student',
    isActive: false,
    department: 'Công nghệ thông tin',
    hasFaceRegistered: true,
    avatar: 'HN',
  },
]

export const INITIAL_CLASSES: ClassItem[] = [
  {
    id: 1,
    classId: 'IT308',
    className: 'Lập trình Web nâng cao',
    teacherId: 2,
    teacherName: 'Nguyễn Thị Lan',
    room: 'Phòng A-301',
    schedule: 'Thứ 4 · 08:00 - 10:00',
    department: 'Khoa Công nghệ thông tin',
    studentCount: 42,
    maxStudents: 45,
    studentIds: ['SV20240128', 'SV20240129', 'SV20240204', 'SV20240312', 'SV20240405'],
  },
  {
    id: 2,
    classId: 'IT204',
    className: 'Cơ sở dữ liệu nâng cao',
    teacherId: 2,
    teacherName: 'Nguyễn Thị Lan',
    room: 'Phòng B-202',
    schedule: 'Thứ 4 · 13:30 - 15:30',
    department: 'Khoa Công nghệ thông tin',
    studentCount: 40,
    maxStudents: 40,
    studentIds: ['SV20240128', 'SV20240129', 'SV20240204', 'SV20230104'],
  },
  {
    id: 3,
    classId: 'SS101',
    className: 'Kỹ năng nghề nghiệp',
    teacherId: 2,
    teacherName: 'Nguyễn Thị Lan',
    room: 'Phòng C-105',
    schedule: 'Thứ 4 · 16:00 - 18:00',
    department: 'Khoa Kỹ năng mềm',
    studentCount: 45,
    maxStudents: 50,
    studentIds: ['SV20240128', 'SV20240312', 'SV20240405'],
  },
  {
    id: 4,
    classId: 'IT405',
    className: 'Phân tích dữ liệu lớn',
    teacherId: 2,
    teacherName: 'Nguyễn Thị Lan',
    room: 'Lab-2 Dãy E',
    schedule: 'Thứ 6 · 08:00 - 10:00',
    department: 'Khoa Trí tuệ nhân tạo',
    studentCount: 32,
    maxStudents: 35,
    studentIds: ['SV20240128', 'SV20240204'],
  },
]

export const INITIAL_SESSIONS: AttendanceSession[] = [
  {
    id: 1,
    sessionId: 'SES-IT308-0911',
    classId: 'IT308',
    className: 'Lập trình Web nâng cao',
    room: 'Phòng A-301',
    startTime: '08:00',
    endTime: '10:00',
    lateAfter: '08:15',
    status: 'active',
    createdBy: 2,
    createdByName: 'Nguyễn Thị Lan',
    createdAt: '2026-09-11 08:00:00',
    totalEnrolled: 42,
    presentCount: 35,
    lateCount: 2,
    absentCount: 5,
  },
  {
    id: 2,
    sessionId: 'SES-IT204-0909',
    classId: 'IT204',
    className: 'Cơ sở dữ liệu nâng cao',
    room: 'Phòng B-202',
    startTime: '13:30',
    endTime: '15:30',
    lateAfter: '13:45',
    status: 'closed',
    createdBy: 2,
    createdByName: 'Nguyễn Thị Lan',
    createdAt: '2026-09-09 13:30:00',
    totalEnrolled: 40,
    presentCount: 38,
    lateCount: 1,
    absentCount: 1,
  },
]

export const INITIAL_ATTENDANCE_LOGS: AttendanceLog[] = [
  {
    id: 1,
    sessionId: 'SES-IT308-0911',
    classId: 'IT308',
    studentId: 'SV20240128',
    studentName: 'Trần Minh Khoa',
    checkInTime: '08:02:15',
    confidenceScore: 98.4,
    status: 'present',
    reviewStatus: 'approved',
    method: 'Khuôn mặt',
    createdAt: '2026-09-11 08:02:15',
  },
  {
    id: 2,
    sessionId: 'SES-IT308-0911',
    classId: 'IT308',
    studentId: 'SV20240129',
    studentName: 'Nguyễn Minh Anh',
    checkInTime: '08:03:12',
    confidenceScore: 95.8,
    status: 'present',
    reviewStatus: 'approved',
    method: 'Khuôn mặt',
    createdAt: '2026-09-11 08:03:12',
  },
  {
    id: 3,
    sessionId: 'SES-IT308-0911',
    classId: 'IT308',
    studentId: 'SV20240204',
    studentName: 'Trần Quốc Huy',
    checkInTime: '07:59:45',
    confidenceScore: 67.2,
    status: 'present',
    reviewStatus: 'pending',
    method: 'Khuôn mặt',
    createdAt: '2026-09-11 07:59:45',
  },
  {
    id: 4,
    sessionId: 'SES-IT308-0911',
    classId: 'IT308',
    studentId: 'SV20240312',
    studentName: 'Lê Phương Thảo',
    checkInTime: '08:01:09',
    confidenceScore: 82.0,
    status: 'present',
    reviewStatus: 'pending',
    method: 'Khuôn mặt',
    createdAt: '2026-09-11 08:01:09',
  },
  {
    id: 5,
    sessionId: 'SES-IT308-0911',
    classId: 'IT308',
    studentId: 'SV20240405',
    studentName: 'Phạm Gia Bảo',
    checkInTime: '08:18:32',
    confidenceScore: 61.5,
    status: 'late',
    reviewStatus: 'pending',
    method: 'Khuôn mặt',
    createdAt: '2026-09-11 08:18:32',
  },
]

export const INITIAL_COMPLAINTS: ComplaintRequest[] = [
  {
    id: 1,
    requestId: 'CMP-2026-001',
    sessionId: 'SES-IT308-0909',
    className: 'Lập trình Web nâng cao',
    studentId: 'SV20240128',
    studentName: 'Trần Minh Khoa',
    reason: 'Em có mặt lúc 08:05 nhưng camera bị chói ánh sáng cửa sổ nên không ghi nhận được khuôn mặt. Em ngồi bàn 3 dãy ngoài cùng.',
    requestStatus: 'pending',
    createdAt: '2026-09-10 09:30:00',
  },
  {
    id: 2,
    requestId: 'CMP-2026-002',
    sessionId: 'SES-IT204-0909',
    className: 'Cơ sở dữ liệu nâng cao',
    studentId: 'SV20240204',
    studentName: 'Trần Quốc Huy',
    reason: 'Xin xác nhận vắng mặt có phép do đi khám bệnh theo giấy hẹn của bệnh viện đại học Y.',
    requestStatus: 'approved',
    teacherNote: 'Đã nhận giấy phép hợp lệ qua email. Duyệt điểm danh có phép.',
    createdAt: '2026-09-09 16:45:00',
    resolvedAt: '2026-09-10 08:15:00',
  },
  {
    id: 3,
    requestId: 'CMP-2026-003',
    sessionId: 'SES-SS101-0908',
    className: 'Kỹ năng nghề nghiệp',
    studentId: 'SV20230104',
    studentName: 'Vũ Hoàng Nam',
    reason: 'Hệ thống báo vắng nhưng em có phát biểu trong bài tập nhóm phần 2.',
    requestStatus: 'rejected',
    teacherNote: 'Kiểm tra camera phòng C-105 không thấy sinh viên tham gia phiên học.',
    createdAt: '2026-09-09 10:15:00',
    resolvedAt: '2026-09-09 14:00:00',
  },
  {
    id: 4,
    requestId: 'CMP-2026-004',
    sessionId: 'SES-IT308-0909',
    className: 'Lập trình Web nâng cao',
    studentId: 'SV20240312',
    studentName: 'Lê Phương Thảo',
    reason: 'Hệ thống báo muộn 1 phút do lỗi mạng khi kết nối vào camera nhận diện tại cửa lớp.',
    requestStatus: 'pending',
    createdAt: '2026-09-10 11:20:00',
  },
]

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 1,
    time: '09:14',
    action: 'Cập nhật vai trò người dùng',
    actor: 'Phạm Đức Long · Quản trị viên',
    detail: 'Đã gán quyền Giảng viên cho tài khoản Trần Văn Hùng (GV2019011)',
    tone: 'teal',
    timestamp: '2026-09-11 09:14:00',
  },
  {
    id: 2,
    time: '08:58',
    action: 'Khóa tài khoản sinh viên',
    actor: 'Phạm Đức Long · Quản trị viên',
    detail: 'Khóa tài khoản SV20230104 do vi phạm quy chế điểm danh hộ',
    tone: 'amber',
    timestamp: '2026-09-11 08:58:00',
  },
  {
    id: 3,
    time: '08:31',
    action: 'Xuất báo cáo điểm danh CSV',
    actor: 'Nguyễn Thị Lan · Giảng viên',
    detail: 'Xuất báo cáo chuyên cần lớp IT308 (Lập trình Web nâng cao)',
    tone: 'blue',
    timestamp: '2026-09-11 08:31:00',
  },
  {
    id: 4,
    time: '08:05',
    action: 'Đăng nhập hệ thống thành công',
    actor: 'Trần Minh Khoa · Sinh viên',
    detail: 'Đăng nhập từ IP 192.168.100.116 - Trình duyệt Chrome',
    tone: 'teal',
    timestamp: '2026-09-11 08:05:00',
  },
  {
    id: 5,
    time: '08:00',
    action: 'Mở phiên điểm danh mới',
    actor: 'Nguyễn Thị Lan · Giảng viên',
    detail: 'Khởi tạo phiên SES-IT308-0911 tại Phòng A-301',
    tone: 'teal',
    timestamp: '2026-09-11 08:00:00',
  },
]

export const SYSTEM_HEALTH: SystemHealth = {
  apiStatus: 'Hoạt động ổn định (Healthy)',
  apiUptime: 99.9,
  aiServiceStatus: 'InsightFace ArcFace 512D Ready',
  aiUptime: 98.7,
  dbStatus: 'MySQL 8.0 Connected (Pool: 12/20)',
  dbUptime: 100,
  activeWsConnections: 42,
  avgLatencyMs: 46,
}
