"""Init V1 Schema

Revision ID: 1a19e190315a
Revises: 
Create Date: 2026-09-18 00:46:10.272904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a19e190315a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('course_code', sa.String(length=30), nullable=False),
    sa.Column('course_name', sa.String(length=200), nullable=False),
    sa.Column('credits', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('credits BETWEEN 1 AND 20', name='ck_courses_credits'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_code')
    )
    op.create_table('semesters',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'ACTIVE', 'CLOSED', name='semesterstatusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('end_date >= start_date', name='ck_semesters_dates'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'LECTURER', 'ADMIN', name='roleenum'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'LOCKED', name='userstatusenum'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor_user_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=True),
    sa.Column('entity_id', sa.String(length=80), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_action_time', 'audit_logs', ['action', 'created_at'], unique=False)
    op.create_index('idx_audit_actor_time', 'audit_logs', ['actor_user_id', 'created_at'], unique=False)
    op.create_index('idx_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('lecturers',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('lecturer_code', sa.String(length=30), nullable=False),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('academic_title', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('lecturer_code')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('replaced_by_token_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['replaced_by_token_id'], ['refresh_tokens.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('idx_tokens_user_expiry', 'refresh_tokens', ['user_id', 'expires_at'], unique=False)
    op.create_table('students',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('student_code', sa.String(length=30), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('cohort', sa.String(length=20), nullable=True),
    sa.Column('major', sa.String(length=100), nullable=True),
    sa.Column('administrative_class', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('student_code')
    )
    op.create_table('class_sections',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('section_code', sa.String(length=40), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('semester_id', sa.BigInteger(), nullable=False),
    sa.Column('lecturer_id', sa.BigInteger(), nullable=False),
    sa.Column('room', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'OPEN', 'CLOSED', 'CANCELLED', name='sectionstatusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lecturer_id'], ['lecturers.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('semester_id', 'section_code', name='uk_sections_semester_code')
    )
    op.create_table('face_profiles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('embedding_dimension', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'REVOKED', name='faceprofilestatusenum'), nullable=False),
    sa.Column('consent_at', sa.DateTime(), nullable=False),
    sa.Column('enrolled_by', sa.BigInteger(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['enrolled_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_face_profiles_status'), 'face_profiles', ['status'], unique=False)
    op.create_index(op.f('ix_face_profiles_student_id'), 'face_profiles', ['student_id'], unique=False)
    op.create_table('attendance_sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('section_id', sa.BigInteger(), nullable=False),
    sa.Column('session_no', sa.SmallInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('scheduled_start_at', sa.DateTime(), nullable=False),
    sa.Column('scheduled_end_at', sa.DateTime(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('late_after_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'OPEN', 'CLOSED', 'CANCELLED', name='sessionstatusenum'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('late_after_at >= scheduled_start_at AND late_after_at <= scheduled_end_at', name='ck_sessions_late_after'),
    sa.CheckConstraint('scheduled_end_at > scheduled_start_at', name='ck_sessions_schedule'),
    sa.ForeignKeyConstraint(['created_by'], ['lecturers.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['section_id'], ['class_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'session_no', name='uk_sessions_section_no')
    )
    op.create_index(op.f('ix_attendance_sessions_scheduled_start_at'), 'attendance_sessions', ['scheduled_start_at'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_section_id'), 'attendance_sessions', ['section_id'], unique=False)
    op.create_table('enrollments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('section_id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('ENROLLED', 'DROPPED', 'COMPLETED', name='enrollmentstatusenum'), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['class_sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'student_id', name='uk_enrollments_section_student')
    )
    op.create_table('face_embeddings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('face_profile_id', sa.BigInteger(), nullable=False),
    sa.Column('embedding_data', sa.JSON(), nullable=False),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('image_uri', sa.String(length=500), nullable=True),
    sa.Column('image_checksum', sa.String(length=64), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('quality_score BETWEEN 0 AND 1', name='ck_embeddings_quality'),
    sa.ForeignKeyConstraint(['face_profile_id'], ['face_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_face_embeddings_face_profile_id'), 'face_embeddings', ['face_profile_id'], unique=False)
    op.create_index(op.f('ix_face_embeddings_is_primary'), 'face_embeddings', ['is_primary'], unique=False)
    op.create_table('attendance_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'LATE', 'ABSENT', 'EXCUSED', name='attendancestatusenum'), nullable=False),
    sa.Column('verification_method', sa.Enum('FACE', 'MANUAL', 'IMPORT', name='verificationmethodenum'), nullable=False),
    sa.Column('check_in_at', sa.DateTime(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('liveness_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('evidence_image_uri', sa.String(length=500), nullable=True),
    sa.Column('review_status', sa.Enum('AUTO_APPROVED', 'PENDING', 'APPROVED', 'REJECTED', name='reviewstatusenum'), nullable=False),
    sa.Column('reviewed_by', sa.BigInteger(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('confidence_score IS NULL OR (confidence_score BETWEEN 0 AND 1)', name='ck_attendance_confidence'),
    sa.CheckConstraint('liveness_score IS NULL OR (liveness_score BETWEEN 0 AND 1)', name='ck_attendance_liveness'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['lecturers.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'student_id', name='uk_attendance_session_student')
    )
    op.create_index(op.f('ix_attendance_records_session_id'), 'attendance_records', ['session_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_student_id'), 'attendance_records', ['student_id'], unique=False)
    op.create_table('attendance_appeals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('attendance_record_id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence_uri', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='appealstatusenum'), nullable=False),
    sa.Column('resolved_by', sa.BigInteger(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attendance_record_id'], ['attendance_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['lecturers.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attendance_record_id', 'student_id', name='uk_appeals_record_student')
    )
    op.create_index(op.f('ix_attendance_appeals_status'), 'attendance_appeals', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_appeals_status'), table_name='attendance_appeals')
    op.drop_table('attendance_appeals')
    op.drop_index(op.f('ix_attendance_records_student_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_session_id'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_face_embeddings_is_primary'), table_name='face_embeddings')
    op.drop_index(op.f('ix_face_embeddings_face_profile_id'), table_name='face_embeddings')
    op.drop_table('face_embeddings')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_attendance_sessions_section_id'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_scheduled_start_at'), table_name='attendance_sessions')
    op.drop_table('attendance_sessions')
    op.drop_index(op.f('ix_face_profiles_student_id'), table_name='face_profiles')
    op.drop_index(op.f('ix_face_profiles_status'), table_name='face_profiles')
    op.drop_table('face_profiles')
    op.drop_table('class_sections')
    op.drop_table('students')
    op.drop_index('idx_tokens_user_expiry', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('lecturers')
    op.drop_index('idx_audit_entity', table_name='audit_logs')
    op.drop_index('idx_audit_actor_time', table_name='audit_logs')
    op.drop_index('idx_audit_action_time', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('semesters')
    op.drop_table('courses')
    # ### end Alembic commands ###
